-- MySQL Script generated by MySQL Workbench
-- Wed Dec  7 00:11:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `experience` INT NULL,
  `specialty` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `facilityId` INT NULL,
  `Doctor_id` INT NOT NULL,
  `Patients_id` INT NOT NULL,
  `Room_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Doctor_id`, `Patients_id`, `Room_id`),
  INDEX `fk_Session_Doctor_idx` (`Doctor_id` ASC) VISIBLE,
  INDEX `fk_Session_Patients1_idx` (`Patients_id` ASC) VISIBLE,
  INDEX `fk_Session_Room1_idx` (`Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Session_Doctor`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Session_Patients1`
    FOREIGN KEY (`Patients_id`)
    REFERENCES `mydb`.`Patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Session_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `mydb`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facility` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `available` TINYINT NULL,
  `roomId` INT NULL,
  `Room_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Room_id`),
  INDEX `fk_Facility_Room1_idx` (`Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Facility_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `mydb`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Illness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Illness` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `stage` VARCHAR(45) NULL,
  `metastation` VARCHAR(45) NULL,
  `lypmphNodes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BodyPart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BodyPart` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Illness_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Illness_id`),
  INDEX `fk_BodyPart_Illness1_idx` (`Illness_id` ASC) VISIBLE,
  CONSTRAINT `fk_BodyPart_Illness1`
    FOREIGN KEY (`Illness_id`)
    REFERENCES `mydb`.`Illness` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report` (
  `id` INT NOT NULL,
  `content` TEXT(600) NULL,
  `createAt` DATETIME NULL,
  `Illness_id` INT NOT NULL,
  `Session_id` INT NOT NULL,
  `Session_Doctor_id` INT NOT NULL,
  `Session_Patients_id` INT NOT NULL,
  `Session_Room_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Illness_id`, `Session_id`, `Session_Doctor_id`, `Session_Patients_id`, `Session_Room_id`),
  INDEX `fk_Report_Illness1_idx` (`Illness_id` ASC) VISIBLE,
  INDEX `fk_Report_Session1_idx` (`Session_id` ASC, `Session_Doctor_id` ASC, `Session_Patients_id` ASC, `Session_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Report_Illness1`
    FOREIGN KEY (`Illness_id`)
    REFERENCES `mydb`.`Illness` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Session1`
    FOREIGN KEY (`Session_id` , `Session_Doctor_id` , `Session_Patients_id` , `Session_Room_id`)
    REFERENCES `mydb`.`Session` (`id` , `Doctor_id` , `Patients_id` , `Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feedback` (
  `id` INT NOT NULL,
  `content` TEXT(600) NULL,
  `createdAt` DATETIME NULL,
  `Session_id` INT NOT NULL,
  `Session_Doctor_id` INT NOT NULL,
  `Session_Patients_id` INT NOT NULL,
  `Session_Room_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Session_id`, `Session_Doctor_id`, `Session_Patients_id`, `Session_Room_id`),
  INDEX `fk_Feedback_Session1_idx` (`Session_id` ASC, `Session_Doctor_id` ASC, `Session_Patients_id` ASC, `Session_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_Session1`
    FOREIGN KEY (`Session_id` , `Session_Doctor_id` , `Session_Patients_id` , `Session_Room_id`)
    REFERENCES `mydb`.`Session` (`id` , `Doctor_id` , `Patients_id` , `Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
